services:
    ant_qa.payu_bundle.controller.payment:
        class:     AntQa\Bundle\PayUBundle\Controller\PaymentController
        arguments: ["@doctrine.orm.entity_manager", "%payu_bundle.payment_class%"]
